CREATE TABLE books(
	isbn CHAR(17) PRIMARY KEY
	,title VARCHAR(100) NOT NULL
	,price INT NOT NULL
	,publisher VARCHAR(20) NOT NULL
	,published DATE NOT NULL
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME　NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE book_stocks(
	isbn CHAR(17) PRIMARY KEY
	,stock_num INT NOT NULL
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,CONSTRAINT fk_book_stocks_isbn FOREIGN KEY (isbn)
	  REFERENCES books(isbn)
);

CREATE TABLE customers(
	customer_id INT PRIMARY KEY AUTO_INCREMENT
	,name VARCHAR(20) NOT NULL
	,tel CHAR(13) NOT NULL
	,post_num CHAR(8) NOT NULL
	,address VARCHAR(50) NOT NULL
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);

CREATE TABLE order_histories(
	order_id INT PRIMARY KEY AUTO_INCREMENT
	,customer_id INT NOT NULL
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,CONSTRAINT fk_order_histories_customer_id FOREIGN KEY
	 (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_items(
	item_id INT PRIMARY KEY AUTO_INCREMENT
	,order_id INT NOT NULL
	,isbn CHAR(17) NOT NULL
	,num INT NOT NULL
	,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--	,CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id)
--	REFERENCES order_histories(order_id)
	,CONSTRAINT fk_order_items_isbn FOREIGN KEY (isbn)
	 REFERENCES books(isbn)	
);
